"""
Phase 5: Streamlit UI for NYC Building Code RAG.

Displays: question box → answer + confidence badge + expandable cited
sections + disclaimer.  Talks to the FastAPI backend at /ask.
"""

from __future__ import annotations

import os

import httpx
import streamlit as st
from dotenv import load_dotenv

load_dotenv()

API_URL = os.getenv("API_URL", "http://localhost:8000")

DISCLAIMER = (
    "**Disclaimer:** This tool is a reference aid only and is **not** a substitute "
    "for advice from a New York State–licensed architect, engineer, or code consultant. "
    "Always verify requirements with the current adopted code and the NYC Department of Buildings."
)

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="NYC Building Code Assistant",
    page_icon="🏗️",
    layout="wide",
)

st.title("🏗️ NYC Building Code Assistant")
st.caption("2022 Edition — Ask questions, get plain-language answers with exact code citations.")

st.warning(DISCLAIMER)

# ---------------------------------------------------------------------------
# Sidebar: settings
# ---------------------------------------------------------------------------

with st.sidebar:
    st.header("Search settings")
    top_k = st.slider("Results to retrieve (top-k)", min_value=3, max_value=20, value=8)
    alpha = st.slider(
        "Hybrid balance (α)",
        min_value=0.0,
        max_value=1.0,
        value=0.75,
        step=0.05,
        help="1.0 = pure semantic, 0.0 = pure keyword",
    )
    chapter_filter = st.text_input(
        "Filter by chapter (optional)",
        placeholder="e.g. 16",
        help="Leave blank to search all chapters.",
    )
    st.markdown("---")
    st.markdown("**About**")
    st.markdown(
        "Answers are generated by an LLM grounded strictly in retrieved code sections. "
        "Every claim is backed by a citation."
    )


# ---------------------------------------------------------------------------
# Confidence badge helper
# ---------------------------------------------------------------------------

def confidence_badge(score: float) -> str:
    if score >= 0.75:
        return f"🟢 High confidence ({score:.0%})"
    if score >= 0.45:
        return f"🟡 Medium confidence ({score:.0%})"
    return f"🔴 Low confidence ({score:.0%})"


# ---------------------------------------------------------------------------
# Main query flow
# ---------------------------------------------------------------------------

question = st.text_area(
    "Your question",
    height=80,
    placeholder="e.g. What is the minimum required occupant load for a 500 sq ft assembly space?",
)

ask_btn = st.button("Ask", type="primary", use_container_width=False)

if ask_btn and question.strip():
    with st.spinner("Searching code sections and generating answer…"):
        try:
            payload = {
                "question": question.strip(),
                "top_k": top_k,
                "alpha": alpha,
            }
            if chapter_filter.strip():
                payload["chapter_filter"] = chapter_filter.strip()

            resp = httpx.post(f"{API_URL}/ask", json=payload, timeout=60)
            resp.raise_for_status()
            data = resp.json()

        except httpx.ConnectError:
            st.error(
                "Cannot connect to the API. Make sure the FastAPI server is running "
                f"at {API_URL} (or run `docker-compose up`)."
            )
            st.stop()
        except Exception as e:
            st.error(f"Request failed: {e}")
            st.stop()

    # --- Answer ---
    st.subheader("Answer")
    if data.get("insufficient"):
        st.info(data["answer"])
    else:
        st.markdown(data["answer"])

    col1, col2 = st.columns([2, 1])
    with col1:
        cited = data.get("cited_sections", [])
        if cited:
            st.markdown("**Cited sections:** " + ", ".join(f"§{s}" for s in cited))
    with col2:
        st.markdown(confidence_badge(data.get("confidence", 0.0)))

    # --- Source sections ---
    if data.get("sources"):
        st.subheader("Source Sections")
        for src in data["sources"]:
            label = f"§{src['section_number']} — {src['section_title']}  (Chapter {src['chapter']})"
            with st.expander(label):
                st.markdown(f"**Score:** {src['score']:.4f}  |  Pages {src['page_start']}–{src['page_end']}")
                st.markdown(src["text"])

elif ask_btn:
    st.warning("Please enter a question.")
